In [33]:
import numpy as np

In [38]:
W = np.array([[0, -1.5],[-1.5, 0]])
ps = [[], [1],[2],[1,2]]
matrix_size = len(W)

In [39]:
A = np.copy(W)
for entry in ps:
    W = np.copy(A)
    t_s = np.ones((matrix_size, 1))
    print(ps.index(entry))
    i = ps[ps.index(entry)]
    if entry:
        for iter in i:
            W[iter-1, :] = 0
            inverse = np.linalg.inv(np.identity(matrix_size) - W)   
            t_s[iter-1, :] = 0
            P = np.matmul(inverse, t_s)
        print(P)
    else:
        inverse = np.linalg.inv(np.identity(matrix_size) - W)
        P = np.matmul(inverse, t_s)
        print(P)

0
[[0.4]
 [0.4]]
1
[[0.]
 [1.]]
2
[[1.]
 [0.]]
3
[[0.]
 [0.]]


In [45]:
W = np.array([[0, -1.25],[-1.25, 0]])
x = []
t = 1
e = 0.25
d = 0.5
sigma = [1]
t_s = np.array([[1],[1]])

for i in range(matrix_size):
    hp_entry = input('insert hyperplane equations in ascending order\n')
    x.append(eval(hp_entry))

def y_i(i,j):
    y_i = W[i, j]*x[j] + t_s
    return(y_i)
for i in range(matrix_size):
    if i+1 in sigma:
        for j in range(matrix_size):
            if i == j:
                break
            check = y_i(i, j)

print(x)


SyntaxError: invalid syntax (<string>, line 0)