In [26]:
import numpy as np
import random as rd
d = 0.5
e = 0.25

matrix_size = int(input('matrix size?\n'))
mat = np.zeros((matrix_size, matrix_size))

possible_vals = (-2,-1,1,2)
weights = (0.2,0.3, 0.3,0.2)

for i in range(matrix_size):
    for j in range(matrix_size):
        if i == j:
            continue
        else:
            mat[i,j] = rd.choices(possible_vals, weights)[0]

for i in range(matrix_size):
    for j in range(matrix_size):
        if mat[i,j] == -2:
            mat[i,j] = -1-d
            mat[j,i] = -1-d
        if mat[i,j] == 2:
            mat[i,j] = -1+e
            mat[j,i] = -1+e
        if mat[i,j] == -1:
            mat[i,j] = -1-d
        if mat[i,j] == 1:
            mat[i,j] = -1+e

print(mat)

[[ 0.   -1.5 ]
 [-0.75  0.  ]]


In [6]:
import numpy as np

d=0.5
e=0.25


In [17]:
def weight_matrix_bal(matrix_size,p,q):
    mat = np.zeros((matrix_size, matrix_size))

    sc_p = (p*10)/matrix_size
    sc_q = (q*10)/matrix_size

    print(sc_p)
    print(sc_q)

    possible_vals = (-2,-1,1,2)
    weights = (1-p,sc_p*((1-sc_q)/2),sc_p*((1-sc_q)/2),sc_p*sc_q)

    for i in range(matrix_size):
        for j in range(matrix_size):
            if i >= j:
                continue
            else:
                mat[i,j] = np.random.choice(possible_vals, 1, weights)[0]
    print(mat)

    for i in range(matrix_size):
        for j in range(matrix_size):
            # if mat[i,j] == -2:
            #     mat[i,j] = -1-d
            #     mat[j,i] = -1-d
            if mat[i,j] == 2:
                mat[i,j] = -1+e
                mat[j,i] = -1+e
            if mat[i,j] == -2:
                mat[i,j] = -1-d
                mat[j,i] = -1-d
            if mat[i,j] == -1:
                mat[i,j] = -1-d
                mat[j,i] = -1+e
            if mat[i,j] == 1:
                mat[i,j] = -1+e
                mat[j,i] = -1-d



    print(mat)
    return(mat)

In [18]:
weight_matrix_bal(7,0.6,0.1)

0.8571428571428571
0.14285714285714285
[[ 0.  2.  1. -2.  1. -1.  1.]
 [ 0.  0.  1. -1.  1. -1.  1.]
 [ 0.  0.  0.  1.  2. -2.  1.]
 [ 0.  0.  0.  0.  1. -1.  1.]
 [ 0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.   -0.75 -0.75 -1.5  -0.75 -1.5  -0.75]
 [-0.75  0.   -0.75 -1.5  -0.75 -1.5  -0.75]
 [-1.5  -1.5   0.   -0.75 -0.75 -1.5  -0.75]
 [-1.5  -0.75 -1.5   0.   -0.75 -1.5  -0.75]
 [-1.5  -1.5  -0.75 -1.5   0.   -0.75 -1.5 ]
 [-0.75 -0.75 -1.5  -0.75 -1.5   0.   -0.75]
 [-1.5  -1.5  -1.5  -1.5  -0.75 -0.75  0.  ]]


array([[ 0.  , -0.75, -0.75, -1.5 , -0.75, -1.5 , -0.75],
       [-0.75,  0.  , -0.75, -1.5 , -0.75, -1.5 , -0.75],
       [-1.5 , -1.5 ,  0.  , -0.75, -0.75, -1.5 , -0.75],
       [-1.5 , -0.75, -1.5 ,  0.  , -0.75, -1.5 , -0.75],
       [-1.5 , -1.5 , -0.75, -1.5 ,  0.  , -0.75, -1.5 ],
       [-0.75, -0.75, -1.5 , -0.75, -1.5 ,  0.  , -0.75],
       [-1.5 , -1.5 , -1.5 , -1.5 , -0.75, -0.75,  0.  ]])